# Default values for gke-node-startup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proxy:
  method: "http"
  # Its recommended to provide an up rather than a DNS name due to dns issues that might arise when configuring a proxy.
  host: "10.10.10.10"
  port: "8080"
  # GKE Control plane IP should be added as well in order to bypass proxy
  no_proxy: "googleapis.com,.svc,localhost,127.0.0.1,metadata.google.internal."

imagePullTest:
  enabled: true
  image: nicolaka/netshoot:latest

image:
  # Repository must be a GCR repository with GSA/KSA permissions to pull images
  # Please make sure the image exists before running this chart
  repository: europe-west3-docker.pkg.dev/PROJECT/cellwize/google/cloud-sdk
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations:
  - key: "gke-node-pool"
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}
