{{- if .Values.imagePullTest.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gke-node-startup.fullname" . }}-image-pull-test
  labels:
    app: image-pull-test
spec:
  selector:
    matchLabels:
      app: image-pull-test
  template:
    metadata:
      labels:
        app: image-pull-test
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gke-node-startup.serviceAccountName" . }}
      hostPID: true
      initContainer:
        - name: {{ .Chart.Name }}-image-pull-test
          image: "{{ .Values.imagePullTest.image }}"
          imagePullPolicy: Always


          args:
            - /bin/sh
            - -c
            - date
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}